### ISSUE TITLE
Get domain for our website

### ISSUE THREAD

**Issue by tsaoyu** [Maritime-Robotics-Student-Society/Maritime-Robotics-Student-Society.github.io#1]
`Maritime-Robotics-Student-Society.github.io` is bit too long as our domain. 
We shall decide and buy a more proper domain for our website. 

Suggestions are welcomed!

**Comment by zysim** [comment]
I support Thomas' suggestion personally

**Comment by takluyver** [comment]
My suggestion was `sotonsailbot` with probably either `.co.uk`/`.org.uk` (£7/year) or `.org` (£12/year) as an extension.

I registered my personal domain with 123-reg; I don't know if there are better options, but I haven't had any problems with them.

**Comment by tsaoyu** [comment]
Sophia and I prefer `sotonsailrobot` to distinguish us from boat dealers.
And that domain is in consistency with our twitter and email.
