### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by tsaoyu** [Maritime-Robotics-Student-Society/Maritime-Robotics-Student-Society.github.io#6]
Configure CI file for automatic build and deploy.

**Comment by zysim** [comment]
Turns out we never needed this lol. In `#24` in [the docs](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll#creating-your-site), public repos already have this pre-configured:

> If your GitHub Pages site is built from a public repository, it is built and deployed with a GitHub Actions workflow run unless you've configured your GitHub Pages site to use a different CI tool.
